image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.6.0

stages:
  - docker-build

docker-test-build:
  stage: docker-build
  script:
    - docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} .
  only:
    - /^feature-.*$/
    - /^bugfix-.*$/

docker-build:
  stage: docker-build
  script:
    - docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} .
    - docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    - chart_build
  only:
    - tags
    - master
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/

.auto_devops: &auto_devops |
    http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
    if [ "$http_status_code" != "200" ]; then
      cat .auto_devops.sh
      exit 1
    fi
    source .auto_devops.sh

before_script:
  - *auto_devops
